require 'muesli/attribute_serializers/base'
require 'muesli/attribute_serializers/time'
require 'muesli/attribute_serializers/date'
require 'muesli/attribute_serializers/date_time'
require 'muesli/attribute_serializers/moped_bson_objectid'
require 'muesli/attribute_serializers/bson_objectid'
require 'muesli/serializers/base'
require 'muesli/adapters/cancan'
